function [C,L] = cir_wprec(C,L,N,cc,ll,wname,which_bands)
% [C,L] = CIR_WPREC(C, L, N, CC, LL, 'wname', WHICH_BANDS)
%   Restores the {C,L} structure returned by CIR_WAVEDEC.M
%   from the cell arrays CC and LL at level N.
%   CC and LL are generated by CIR_WPDEC.M.  

% $Id: cir_wprec.m,v 1.1 2002/01/30 01:34:14 yrchen Exp yrchen $ yrchen@mit.edu 
 
nd = ndims(C);
if ischar(which_bands)
  which_bands = {which_bands};
end

for i = 1:length(which_bands) % loops through WHICH_BANDS(:)
  if nd ~= length(which_bands{i})
    error('CIR_WPREC.M: Length of WHICH_BANDS(i) is not equal to NDIMS(C).');
  end
  curr_band = which_bands{i};
  
  % Get sub_input from C based on curr_band...
  sub_input = cir_waverec_full(cc{i}, ll{i}, wname);
  C = md_setpkt(C, L, N, curr_band, sub_input);  
end
