%%%%%%%%%%%%%%%  MakeDefaultQTMovieStatus %%%%%%%%%%%%%%%%%
% Make the default movie status structure.
function MakeDefaultQTMovieStatus
global MakeQTMovieStatus
if isempty(MakeQTMovieStatus)
   MakeQTMovieStatus = struct(...
      'frameRate', 10, ...	% frames per second
      'frameStarts', [], ...  % Starting byte position
      'frameLengths', [], ...
      'timeScale', 10, ...	% How much faster does time run?
      'soundRate', 22050, ... % Sound Sample Rate
      'soundStart', [], ...	% Starting byte position
      'soundLength', 0, ...
      'soundChannels', 1, ...	% Number of channels
      'frameNumber', 0, ...
      'movieFp', [], ...		% File pointer 
      'imageTmp', tempname, ...
      'movieName', 'output.mov', ...
      'imageSize', [0 0], ...
      'trackNumber', 0, ...
      'timeScaleExpansion', 100, ...
      'spatialQual', 1.0);	% Between 0.0 and 1.0
end
